version: "3.7"

services:
        postgres:
                image: postgres:12.6-alpine
                environment:
                        POSTGRES_PASSWORD: test
                container_name: postgres
        frontend:
                build: frontend/.
                ports:
                        - 5000:5000
                depends_on:
                        - backend
        backend:
                build: ./backend/
                environment:
                        POSTGRES_HOST: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: test
                        POSTGRES_DATABASE: postgres
                        REDIS_HOST: redis
                        REQUEST_ORIGIN: http://localhost:5000
                ports:
                        - 8080:8080
                depends_on:
                        - postgres
                        - redis
                restart: unless-stopped
        redis:
                image: redis:6.2
                restart: unless-stopped
                container_name: redis
