version: "3.7"

services:
        backend:
                build: backend
                image: backend:production
                ports:
                        - 8080:8080
        frontend:
                build: frontend
                image: frontend:production
                ports:
                        - 5000:5000
                depends_on:
                        - backend
                        - redis
        redis:
                image: redis:6.2-alpine3.13
                container_name: rediscontainer
                restart: unless-stopped
